apiVersion: skaffold/v1beta2
kind: Config
build: 
  local:
    push: false
  artifacts:
    - image: polyhistor/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      # files to be watched
      sync: 
        '**/*.js': .
        '**/*.css': .
        '**/*.html': .
deploy: 
  kubectl:
    manifests:
      - k8s/client-deployment.yaml