apiVersion: certmanager.k8s.io/v1alpha2
kind: Certificate
metadata: 
  name: grandfungi-com-tls
spec:
  secretName: grandfungi-com
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: grandfungi.com
  dnsNames:
    - grandfungi.com
    - www.grandfungi.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - grandfungi.com
          - www.grandfungi.com