apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: database-persistent-volume-claim
spec:
  accessModes:
  # ReadWriteOnce means only a single node at a time can used the volume, there are two other options
  # ReadOnlyMany which means multilpe nodes can read from the volume and 
  # ReadWriteMany which means multiple nodes can read and write from the volume
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
