apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata: 
  name: ingress-service
  annotations: 
  # the linve above basically tells Kubernetes that we aiming 
  # to create the ingress controller based on nginx project
    kubenetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
    - hosts:
        - grandfungi-com
        - www.grandfungi.com
      secretName: grandfungi-com
  rules:
    - host: grandfungi-com
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
          - path: /api/?(.*)
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 5000
    - host: www.grandfungi-com
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
          - path: /api/?(.*)
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 5000